MODEL:
  WEIGHT: "./models/checkpoints/model_final.pth"
INPUT:
  FLIP_PROB_TRAIN: 0.5
  SHIFT_SCALE_PROB_TRAIN: 0.3
DATASETS:
  DETECT_CLASSES: ("Car",)
  TRAIN: ("kitti_train",)
  TEST: ("kitti_train",)
  TRAIN_SPLIT: "train"
  TEST_SPLIT: "val"
SOLVER:
  BASE_LR: 2.5e-4
  STEPS: (5000, 10000, 18000, 20000, 21000, 22000, 23000, 24000)
  MAX_ITERATION: 25000
  IMS_PER_BATCH: 32
OUTPUT_DIR: "./tools/logs"
